def levFunction():
    print("type in five numbers i will add them all up")
    print("type in the first")
    numberOne = int(input())
    print("type in the second")
    numberTwo = int(input())
    print("type in the third")
    numberThree = int(input())
    print("type in the fourth")
    numberFour = int(input())
    print("type in the fifth and final number")
    numberFive = int(input())
    print(numberOne+numberTwo+numberThree+numberFour+numberFive)
levFunction()
